---
title: 'Institutional Incentives'
subtitle: 'SDS 237: Final Project Checkpoint'
author:
  - Fill
  - Fill
  - Fill
  - Fill
date: "Last updated on `r Sys.Date()`"
output: 
  rmdformats::readthedown:
    df_print: paged
editor_options: 
  chunk_output_type: inline
---

## Purpose and Instructions

This checkpoint aims to document the institutions involved in the production and shaping of your final project dataset. Be sure to commit your code often and push your changes to GitHub. 

## Part 1: Institution Mapping

Below create long lists of institutions involved in each phase of the dataset's production. You should do some research to track down the names of specific government offices, private companies, or other partners involved in each phase. In other words, your list should be more specific than "news outlets" or "legislatures." 

### Data Infrastructure Creation

* 

### Data Collection

* 

### Data Cleaning

* 

### Data Aggregation

* 

### Data Analysis

* 

### Data Dissemination

* 

### Data Consumption

* 


## Part 2: Identify institutions

Select **three** institutions from your list that appear to have the largest influences over the final configuration and scope of the data. For each describe their role in the production or stewardship of the data. You might consider the ways in which this institution incentivizes people involved in data production to collect the data in specific ways, the protocols they enforce regarding data collection, etc. Specific questions you might consider include:

* What is the institution's stated mission? How does this stated mission relate to their data work?
* How is the data work this institution engages in funded?
* What technical infrastructures enable the institution to carry out this data work?
* How transparent is the institution's data work?
* What legal and ethical bodies and infrastructures oversee how this institution conducts their data work?
* What repercussions might this institution face if they were to mishandle the data?

### Institution 1:


### Institution 2:


### Institution 3:


### Institution 4 (optional):